# Generated by Django 4.2.7 on 2025-12-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=100, verbose_name='Nombre (Español)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (English)')),
                ('description_es', models.TextField(blank=True, verbose_name='Descripción (Español)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('equipos', 'Equipos'), ('insumos', 'Insumos'), ('servicios', 'Servicios'), ('innovacion', 'Innovación y Desarrollo')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name_es'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Metplastech Technologies SPA', max_length=200)),
                ('slogan_es', models.CharField(blank=True, max_length=300, verbose_name='Slogan (Español)')),
                ('slogan_en', models.CharField(blank=True, max_length=300, verbose_name='Slogan (English)')),
                ('description_es', models.TextField(blank=True, verbose_name='Descripción (Español)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('about_us_es', models.TextField(blank=True, verbose_name='Sobre nosotros (Español)')),
                ('about_us_en', models.TextField(blank=True, verbose_name='About us (English)')),
                ('mission_es', models.TextField(blank=True, verbose_name='Misión (Español)')),
                ('mission_en', models.TextField(blank=True, verbose_name='Mission (English)')),
                ('vision_es', models.TextField(blank=True, verbose_name='Visión (Español)')),
                ('vision_en', models.TextField(blank=True, verbose_name='Vision (English)')),
                ('phone', models.CharField(default='+569 9615 4315', max_length=20)),
                ('whatsapp', models.CharField(default='+56996154315', max_length=20)),
                ('email', models.EmailField(default='contacto@metplastech.cl', max_length=254)),
                ('address_es', models.TextField(default='Curicó – Región del Maule – Chile', verbose_name='Dirección (Español)')),
                ('address_en', models.TextField(blank=True, default='Curicó – Maule Region – Chile', verbose_name='Address (English)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Company Info',
                'verbose_name_plural': 'Company Info',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Proveedor')),
                ('description_es', models.TextField(blank=True, verbose_name='Descripción (Español)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='suppliers/')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País de origen')),
                ('icon', models.CharField(default='business', help_text='Nombre del icono Material', max_length=50)),
                ('color', models.CharField(default='#0369a1', help_text='Color hexadecimal del proveedor', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=200, verbose_name='Nombre (Español)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (English)')),
                ('short_description_es', models.CharField(blank=True, max_length=300, verbose_name='Descripción corta (Español)')),
                ('short_description_en', models.CharField(blank=True, max_length=300, verbose_name='Short description (English)')),
                ('description_es', models.TextField(blank=True, verbose_name='Descripción (Español)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('slug', models.SlugField()),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU/Código')),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.supplier')),
            ],
            options={
                'ordering': ['order', 'name_es'],
                'unique_together': {('supplier', 'slug')},
            },
        ),
    ]
